local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 1.0  
  publish_frequency: 1.0  
  static_map: false       
  rolling_window: true
  width: 2.5   
  height: 2.5   
  resolution: 0.05    
  transform_tolerance: 1.0  #1.0
  plugins: 
  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"} 
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  inflation_radius: 0.10 
  cost_scaling_factor:  3.0   # exponential rate at which the obstacle cost drops off (default:10)

